In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 640.0 kB/s eta 0:00:01
     ------------ ------------------------- 20.5/61.0 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 406.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 1.3 MB/s eta 0:00:12
   ---------------------------------------- 0.1/15.5 MB 1.0 MB/s eta 0:00:15
   ---------------------------------------- 0.1/15.5 MB 1.0 MB/s eta 0:00:15
   ----------------------------------

In [3]:
# perkalian matriks array

import numpy as np

a = np.array([[[12,3], [4,5],[6,7]]])
b = np.array([[[8,9], [1,2], [3,4]]])

kali = a*b
print(kali)

[[[96 27]
  [ 4 10]
  [18 28]]]


In [4]:
# pengurangan matriks array

import numpy as np

a = np.array([[[5,7], [4,3],[9,11]]])
b = np.array([[[2,8], [5,6], [8,5]]])

kurang = a-b
print(kurang)

[[[ 3 -1]
  [-1 -3]
  [ 1  6]]]


In [5]:
# transpose matriks array

import numpy as np

a = np.array([[6,8,7], [9,3,4], [1,3,2]])
b = np.array([[6,7,7], [3,5,3], [8,6,4]])

transpose_a = np.transpose (a)
transpose_b = np.transpose (b)
print (transpose_a)
print ( transpose_b)

[[6 9 1]
 [8 3 3]
 [7 4 2]]
[[6 3 8]
 [7 5 6]
 [7 3 4]]


In [13]:
# inverse matriks array

import numpy as np

a = np.array([[3,1], [3,3]])
b = np.array([[8,9], [ 3,2]])

inverse_a = np.linalg.inv(a)
inverse_b = np.linalg.inv(b)
print("\nInverse matrkis a:")
print(inverse_a)
print("\nInverse matrkis b:")
print(inverse_b)




Inverse matrkis a:
[[ 0.5        -0.16666667]
 [-0.5         0.5       ]]

Inverse matrkis b:
[[-0.18181818  0.81818182]
 [ 0.27272727 -0.72727273]]


In [9]:
# determinan matriks array

import numpy as np

a = np.array([[3,9], [9,5]])
b = np.array([[5,6], [ 4,1]])

determinan_a = np.linalg.det(a)
determinan_b = np.linalg.det(b)
print("Determinan dari matriks a:", determinan_a) 
print("Determinan dari matriks b:", determinan_b)

Determinan dari matriks a: -66.00000000000003
Determinan dari matriks b: -18.999999999999996
